### ISSUE TITLE
Position biasing

### ISSUE THREAD

**Issue by nerdyprincess** [littlebits/react-popover#1]
![cloud-v5_desktop_tooltip](https://cloud.githubusercontent.com/assets/7749358/6942728/7026ca56-d857-11e4-8c55-cfa4ceeeb74c.jpg)

**Comment by nerdyprincess** [comment]
BTW: No problem to bias to centering buoy in the popover

**Comment by jasonkuhrt** [comment]
> BTW: No problem to bias to centering buoy in the popover

Ok great, but also eventually we should be able to set "preferences" for it do bias another way given there is space for it etc. so hopefully your vision as-is here is totally fine too.

Note to self: This issue brings up a case I didn't think about which is multiple popovers should not overlap each other. This is a nice-to-have, probably to leave as a limitation for now.

**Comment by jasonkuhrt** [comment]
Rephrasing this issue so it is actionable.

### Expose an API to bias the position of the popover.

A spec is needed. Currently the best hint is provided by the image above.
