### ISSUE TITLE
Deprecated React.createClass and React.PropTypes

### ISSUE THREAD

**Issue by madox2** [littlebits/react-popover#100]
React.createClass and React.PropTypes are deprecated from react 15.5., which causes errors in console.

**Comment by jasonkuhrt** [comment]
@madox2 Thanks for reporting!

**Comment by AlexNisnevich** [comment]
+1 to resolving the React.createClass warning.

**Comment by a-x-** [comment]
ping

**Comment by a-x-** [comment]
I'm going do it myself

**Comment by a-x-** [comment]
I just started. Welcome to finish PR
