### ISSUE TITLE
enterExitTransitionDurationMs only applies to the exit animation

### ISSUE THREAD

**Issue by pjrharley** [littlebits/react-popover#107]
Despite the name, the enterExitTransitionDurationMs property only actually applies to the exit animation!

You can see that here in the code:

https://github.com/littlebits/react-popover/blob/v0.4.8/lib/index.js#L338

**Comment by jasonkuhrt** [comment]
@pjrharley Hmmm yes that indeed seems to be the case! PR welcome for this.

**Comment by zrwsk** [comment]
Hi,

please check my PR above :)

Kuba

**Comment by jasonkuhrt** [comment]
Fix released in https://github.com/littlebits/react-popover/releases/tag/0.4.11
