### ISSUE TITLE
Release new version with prop-types fix please

### ISSUE THREAD

**Issue by a-x-** [littlebits/react-popover#111]

**Comment by a-x-** [comment]
ping

**Comment by mucahit** [comment]
+1

**Comment by a-x-** [comment]
ping

**Comment by a-x-** [comment]
😫

**Comment by a-x-** [comment]
I made tmp fork with rebuilded dist: `a-x-/react-popover.git#master`

**Comment by jasonkuhrt** [comment]
I'm going to do this tonight. Sorry for the delays and thanks for the poking!

**Comment by jasonkuhrt** [comment]
Done in [0.4.9](https://github.com/littlebits/react-popover/releases/tag/0.4.9)
