### ISSUE TITLE
Build folder is missing in 0.4.11 

### ISSUE THREAD

**Issue by kritip** [littlebits/react-popover#118]
Latest 0.4.11  has build folder missing. Reverting to 0.4.10 works

**Comment by ASnow** [comment]
Mistake looks like `Module not found: Error: Can't resolve 'react-popover' in 'path'`

**Comment by igorescobar** [comment]
`0.4.11` also breaks eslint, probably because of this :)

**Comment by jasonkuhrt** [comment]
Wow sorry about this people. Can someone give `0.4.14` a try?
