### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by strawstack** [littlebits/react-popover#119]
Installing the module with: "npm install --save react-popover"
Importing with this: "import Popover from 'react-popover'"
Results in the error below when "npm start" is run

Error: Module not found: 'react-popover' 

The react-popover module is present in the "node_modules" folder

**Comment by strawstack** [comment]
Solved. I had to use the following line to import. However, this is unintuitive and should be changed or documented

import Popover from 'react-popover/lib/platform'

**Comment by jasonkuhrt** [comment]
@strawstack Yup its #118. Sorry about this!
