### ISSUE TITLE
Append to node other than body

### ISSUE THREAD

**Issue by dvkndn** [littlebits/react-popover#120]
1) Is it possible to append the popover node to somewhere other than body tag?

(I guess currently not, right?)

2) If not, will you accept a PR to have this as a feature?

3) If you accept a PR, other than this place: https://github.com/littlebits/react-popover/blob/master/lib/react-layer-mixin.js#L11, where should I look into to work on such PR?

**Comment by jasonkuhrt** [comment]
Hey @dvkndn thanks for bringing up this feature request. What's the use-case? I'm curious. I would certainly be open to a PR for this. You seem to have the right section of code pinpointed but threading the configuration from top-level props down to that will be more involved I think. I don't have much time these for react-popover but I will absolutely consider a PR for sure 👍 Thanks!

**Comment by dvkndn** [comment]
Thank you, I will sure take a look and try to have a PR here.

```
<body>
  <div id="root> <--- react app's root
    <div class="dark"> <--- a top react component with class is current theme
      ... <--- I want Popover to be here -> can style with "dark" class above
    </div>
  </div>
  ... <--- currently Popover is here -> can't style
</body>
```

Basically I want to style Popover using css cascaded but without touching body tag

**Comment by jasonkuhrt** [comment]
@dvkndn I'm not sure your use-case is a great one. Using the cascade is its own source of complexity and brittle architecture. I would suggest looking at CSS-in-JS solutions that allow themes to be passed around in the application as a first class value.

**Comment by brownsmith** [comment]
Hi @jasonkuhrt, @dvkndn, this would be a useful feature when it comes to navigating through a popover using a keyboard only. For example, triggering the popover via a CTA with the keyboard means that the popover is now the last element in the DOM, therefore making it impossible to tab into the contents of the popover without further scripting.

**Comment by dvkndn** [comment]
Wow that's a great thing @brownsmith ! I'm about to create an issue to ask how to make tab accessible with this :)) I didn't see that it can be solve with this one

**Comment by pionl** [comment]
Hi, @jasonkuhrt, thank you for the package, works perfectly. I need to use different element because of a fullscreen API. My div is presented in full screen and all the popover must be within the div. Is anyone trying to make the feature?

Best regards,
Martin

**Comment by cbmono** [comment]
Here a Pull Request for this feature request:
https://github.com/littlebits/react-popover/pull/134

Please also check this one out:
https://github.com/littlebits/react-popover/pull/132

**Comment by pionl** [comment]
Cool work @cbmono, at this moment i use my implementation that ads the popover always in the parent (its rewritten from mixin (which should be deprecated in near future). I have some issues when using popover in different popover (when removing, just warnings) so I will check your solution. Thanks!

**Comment by jasonkuhrt** [comment]
Thanks to everyone's feedback here and @cbmono's PR we now have this feature in `0.4.17`.
