### ISSUE TITLE
Low Priority Warning since upgrade to react 15.6.1

### ISSUE THREAD

**Issue by pandabuilder** [littlebits/react-popover#124]
Warning: Accessing factories like React.DOM.noscript has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead. Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories

**Comment by damianmr** [comment]
Same here

**Comment by Betree** [comment]
Fixed in PR #129. 

Migrating to jsx would be the best solution but for now this ensure the compatibility with React 16+

**Comment by jasonkuhrt** [comment]
> Migrating to jsx would be the best solution 

Yup. I'll get around to this one day
