### ISSUE TITLE
Failed to compile - since v0.5

### ISSUE THREAD

**Issue by guillaumervls** [littlebits/react-popover#146]
Hi and thanks for the module,

I updated to v0.5, but now I get :

```
Failed to compile.

./node_modules/react-popover/index.js
Module not found: Can't resolve './build/main' in '<my-project-path>/node_modules/react-popover'
```

I'm using [`create-react-app`](https://github.com/facebookincubator/create-react-app). To reproduce just `create-react-app . && npm install react-popover` then add a `<Popover/>` in `src/App.js`, then `npm start`.

I am missing something ?

Cheers

**Comment by mxmtsk** [comment]
There is a PR for this already: #145
I hope it gets merged quickly too

**Comment by jasonkuhrt** [comment]
`0.5.2` is available now and should fix this and a few others issues.
