### ISSUE TITLE
createPortal is not a function

### ISSUE THREAD

**Issue by a-x-** [littlebits/react-popover#149]
hey, what am I doing wrong?

```
"react-popover": "^0.5.2",
"react": "^15.6.1",
"react-dom": "^15.6.1",
```

```jsx
          <Popover
            isOpen={ @state.delayFormShown }
            body={ @renderDelayForm() }
          >
            <a onClick={ @handleChooseDelay }>
              на конкретную дату
            </a>
          </Popover>
```

**Comment by a-x-** [comment]
oh, I got

I should use React@16.0.0

**Comment by jasonkuhrt** [comment]
This would be more clear with peer deps. PR welcome.

**Comment by timhwang21** [comment]
Hi @jasonkuhrt , I am wondering if this bit from the README can be reconsidered:

> There is no plan to support older versions of this library with back-ported patches and PRs for that purpose are not welcome since it increases maintenance for the authors.

It's a pretty simple check for if `createPortal` exists, with a fallback option of using `unstable_renderSubtreeIntoContainer` if it doesn't (meaning we're on `<16.0`).

If you would be okay with that, I can make a PR.

Thanks!

**Comment by jasonkuhrt** [comment]
@timhwang21 PR welcome!
