### ISSUE TITLE
Typescript issue

### ISSUE THREAD

**Issue by serjiosilent** [littlebits/react-popover#171]
I declare module in typescript:
```
declare module 'react-popover' { 
  const Popover: any;
  export default Popover;
}
```
and importing:
`
import Popover from 'react-popover';
`

And after compile I have an error:
![react-popover](https://user-images.githubusercontent.com/3079339/37597361-ef981624-2b87-11e8-874d-66381624ce18.png)

Have ideas how to fix this? Or I doing something wrong?

Using:
```
react:  16.2.0
react-popover: 0.5.4
typescript: 2.6.2
```

Thanks

**Comment by jakemmarsh** [comment]
You likely have to do `import * as Popover from 'react-popover';`
