### ISSUE TITLE
how can i fix the placement?

### ISSUE THREAD

**Issue by filod** [littlebits/react-popover#24]
like 
`<Popover palcement="left" ></Popover>` ?

**Comment by jasonkuhrt** [comment]
@filod Are you asking for a way to bias/prefer a side when multiple are available? If so then we are already tracking that request in #1.

However and/or are you asking for the ability to set a side and disable automatic positioning (meaning that the popover may overflow its container)?

I am going to be working on this library next week. I will try to resolve the 3-4 most pressing issues then.

**Comment by filod** [comment]
thx for reply, this is just what i need

**Comment by filod** [comment]
also hope i can get 'disable automatic positioning' functionality

**Comment by jasonkuhrt** [comment]
@filod https://github.com/littlebits/react-popover#code-props-preferplace-string-null-code

Ok, given that this feature request is about disabling automatic resolution we should reopen this issue under this new understanding.

**Comment by jasonkuhrt** [comment]
For now you can at least play with the new `preferPlace` feature at http://littlebits.github.io/react-popover/build

**Comment by jasonkuhrt** [comment]
@filod Ok now the semantics you are looking for are implemented too. Check out https://github.com/littlebits/react-popover#propsplace--string--null and you can play with this new feature in the live demo http://littlebits.github.io/react-popover/build/

Cheers.

**Comment by filod** [comment]
LGTM :+1:
