### ISSUE TITLE
Rendering Component just gives 'querySelector' of null`

### ISSUE THREAD

**Issue by enjoylife** [littlebits/react-popover#27]
I'm trying to create a simple popover menu, however im confused about how I actually render my header with a popover? 

I keep getting an `Uncaught TypeError: Cannot read property 'querySelector' of null`

Am I using the api incorrectly?

```
import Popover from 'react-popover';
 
... 

render(){
    var menu = ( <div >Popover Menu</div> )
    var header =  ( <div> Menu Header</div> );
    var popoverProps = {
        body:menu,
        isOpen:true,
        place:'bottom'
    }

    return React.createElement(Popover, popoverProps, header)
}
```

**Comment by jasonkuhrt** [comment]
Looking into it now.

**Comment by jasonkuhrt** [comment]
Thanks to you I found one legitimate bug. I also took the chance to improve the UX on error feedback. Closing soon.

**Comment by jasonkuhrt** [comment]
Here's what the new error message looks like:

<img width="840" alt="screen shot 2015-07-20 at 10 17 53 pm" src="https://cloud.githubusercontent.com/assets/284476/8791772/488970fc-2f2d-11e5-93ff-0ed3c2312760.png">

The React component propTypes are set correctly now, and accordingly the library will also throw an error about the invalid option.

**Comment by jasonkuhrt** [comment]
Try `0.3.3`.
