### ISSUE TITLE
Console log in onResize

### ISSUE THREAD

**Issue by prayogoa** [littlebits/react-popover#29]
There's a console log [here](https://github.com/littlebits/react-popover/blob/master/lib/on-resize.js#L87)

**Comment by jasonkuhrt** [comment]
Thanks I'll fix this soon. PR welcome. Sorry about this silly mistake!

**Comment by jasonkuhrt** [comment]
Thanks, cut a release https://github.com/littlebits/react-popover/releases/tag/v0.3.4
