### ISSUE TITLE
Will you provide a UMD build?

### ISSUE THREAD

**Issue by dustingetz** [littlebits/react-popover#38]

**Comment by jasonkuhrt** [comment]
I'm not very familiar with UMD or the advantages. If there is a ***strong*** use-case I might be open to it.

**Comment by dustingetz** [comment]
UMD build would let me load this library from a script tag. I have a client using a rails asset pipeline that does not include npm, browserify etc. Like many large projects, they choose not to make asset pipeline infrastructure changes at this point of the project.

**Comment by jasonkuhrt** [comment]
Thanks for explaining your use-case. If we see multiple other UMD use-cases being requested we may think about supporting it.

If you really want to use this library in your context today then I suggest forking. I do not think we would accept PR for this because of the burden of maintaining it.
