### ISSUE TITLE
React 0.14.0 compatibility

### ISSUE THREAD

**Issue by gregory90** [littlebits/react-popover#39]
Following errors are visible on React 0.14:
```
Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.
Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.
```
Also when installing package with `npm install react-popover` :
```
@my-project@1.0.0-rc1 /project
├── UNMET PEER DEPENDENCY react@0.14.0-rc1
└── react-popover@0.3.5
```

**Comment by jasonkuhrt** [comment]
Thanks for bringing this to my attention. Adding to the next minor release milestone.

**Comment by jasonkuhrt** [comment]
I'll fix this once react 14 is released.

**Comment by gregory90** [comment]
Any news on this?

**Comment by jasonkuhrt** [comment]
@gregory90 Thanks for pinging about this. News is that this issue needs to be addressed soon. I'm hoping for that to be in the next week or two.

**Comment by khankuan** [comment]
+1

**Comment by jasonkuhrt** [comment]
Hey everyone, update: I'm hoping to have this done on Sunday.
