### ISSUE TITLE
sh: testem: command not found

### ISSUE THREAD

**Issue by dustingetz** [littlebits/react-popover#40]
```
react-popover$ npm run test

> react-popover@0.3.5 test /Users/dustin/src/react-popover
> testem

sh: testem: command not found
```

If I add testem as a devDependency, I get a testem error:

Error: Cannot find module '/Users/dustin/src/react-popover/webpack.test.config.js'

**Comment by jasonkuhrt** [comment]
Will get these working again. Haven't tried it in a while. Thanks.

**Comment by jasonkuhrt** [comment]
Fixed but there's no test to actually see. The few that were there were old and not worth much.
