### ISSUE TITLE
Component keeps listening to events after unmount in certain situations

### ISSUE THREAD

**Issue by clayne11** [littlebits/react-popover#41]
I have found a use case where the Popover component is unmounted without calling exit(), which means the scroll / timer / onOuterAction listeners are all still hooked up. This is causes issues with the next Popover that I use because there are now two actions hooked up to onOuterAction, which means that no matter where I click, even on the Popover, it thinks it's an outer action and closes the Popover.

I propose that exit() be called in componentWillUnmount() {} to be sure that the component gets cleaned up properly.

Current componentWillUmount():

```javascript
  componentWillUnmount: function componentWillUnmount() {
    clearInterval(this.checkLayoutInterval);
  }
```

Suggested componentWillUmount():

```javascript
  componentWillUnmount: function componentWillUnmount() {
    this.exit();
  }
```

**Comment by clayne11** [comment]
PR: https://github.com/littlebits/react-popover/pull/42

**Comment by clayne11** [comment]
After looking a little more deeply exit() is not the right strategy. We need to call untrackPopover().

There are no more render cycles after componentWillUnmount() so there's no opportunity to perform the animation to remove the popover.

There are also places where this change could cause an issue when a node that was expected to exist no longer does. I updated all of those locations to guard against undefined.

**Comment by jasonkuhrt** [comment]
It would be awesome if you can specify the scenario in which this error happens. I would love to reproduce the bug.

**Comment by clayne11** [comment]
Is there a way for me to include Popover library in a CodePen or something similar? Is it hosted on a CDN somewhere?

**Comment by jasonkuhrt** [comment]
Not hosted right now sorry. Not familiar with CodePen very much so not sure what it would take to make this happen. If you just need to point `src="..."` to some built file maybe try the link found in http://littlebits.github.io/react-popover/build/ (http://littlebits.github.io/react-popover/build/index.js?dfd87bb2dcf22552ad36).

**Comment by khankuan** [comment]
+1

**Comment by clayne11** [comment]
To give more detail about when this happens:

1) Create a div that only shows in a certain scenario (for example only renders if this.state.renderDiv === true).
2) Wrap the component in the popover.
3) Open the popover.
4) Set the this.state.renderDiv = false
5) You will now have listeners that didn't get cleaned up and are throwing all kinds of errors.

**Comment by clayne11** [comment]
I will try to get a repro up.

**Comment by clayne11** [comment]
Here's a reproduction: https://github.com/clayne11/react-popover-lifecycle-bug

1) Clone the repo
2) npm install && npm run dev:no-debug
3) Open your browser and console.
4) Click the button that opens the popover.
5) Click in the popover to update the state of the component.
6) Scroll the page. You will see a bunch of setState on unmounted component warnings.

This issue causes a lot of problems if you are trying to use multiple popovers on the same page and have components coming into and out of existence while the popover is open. It can completely stop the popovers from rendering.

**Comment by jasonkuhrt** [comment]
Thanks so much. I will try to take a more serious look in the next two weeks.

**Comment by oliversong** [comment]
+1- seeing this as well

**Comment by clayne11** [comment]
I put a PR a for this, can you please look at it / merge it?

**Comment by jasonkuhrt** [comment]
@clayne11 Finally looking today.

**Comment by jasonkuhrt** [comment]
I think the problem is that when the component is [unmounted](https://github.com/littlebits/react-popover/blob/master/lib/index.js#L431-L433) it does not execute the [`untrackPopover`](https://github.com/littlebits/react-popover/blob/master/lib/index.js#L399-L407) method.

**Comment by clayne11** [comment]
I agree - that 's what I fixed in my PR. There was another related issue as well, which is that the removeEventListener call gets fired sometimes on an element (frameEl) that no longer exists.

**Comment by jasonkuhrt** [comment]
@clayne11 Much thanks for your time on this issue and pardon the problem you have been facing because of it. I left a comment in the PR.
