### ISSUE TITLE
In readme, "bottom" should be "below"

### ISSUE THREAD

**Issue by grassick** [littlebits/react-popover#44]
"above | right | bottom | left" should be "above | right | below | left"

**Comment by jasonkuhrt** [comment]
Was fixed here https://github.com/littlebits/react-popover/commit/ef7dffe907bcc3e10ff0a9759e24880b53bbe129#diff-7bd4a925c695c2eb0eced3872b9b965f.

How did you determine otherwise, am I missing something? Thanks.
