### ISSUE TITLE
Edge border on popover body cut off

### ISSUE THREAD

**Issue by KyleAMathews** [littlebits/react-popover#49]
![screen shot 2015-11-18 at 8 04 33 pm](https://cloud.githubusercontent.com/assets/71047/11262067/a446f732-8e2f-11e5-8bbe-43ce54da51c1.png)

**Comment by KyleAMathews** [comment]
This is also causing the x scroll bar to come alive

**Comment by KyleAMathews** [comment]
(But I should add, other than this, everything else looks fantastic! Pleasant to find a very solid popover component)

**Comment by jasonkuhrt** [comment]
Thanks for reporting this! Seems like it will be easy to reproduce. Hopefully easy to solve. Unsure when a fix will land though.

**Comment by KyleAMathews** [comment]
👍🏻

**Comment by jasonkuhrt** [comment]
@KyleAMathews Can you give me the minimal repro case? I was unable to reproduce via simply putting a border on the `.popover-body`. Screenshot:

<img width="726" alt="screen shot 2015-12-10 at 10 46 09 am" src="https://cloud.githubusercontent.com/assets/284476/11720034/809611a8-9f2b-11e5-9117-f0c94e50831f.png">

**Comment by jasonkuhrt** [comment]
No feedback so closing for now.
