### ISSUE TITLE
Example in JSX

### ISSUE THREAD

**Issue by uccio83** [littlebits/react-popover#50]
Is it possible to use this plugin in JSX? Do you have an example?
Something like:

    renderBody() {
        return <p>content</p>
    }
    
    <Popover isOpen={state.isOpen} body={renderBody}>
        <a href="#">my popover opener</a>
    </Popover>

**Comment by isnifer** [comment]
+

**Comment by isnifer** [comment]
And example when `popover opener` outside the popover, like this:
```jsx
<span>my popover opener</span>
<span>my popover opener</span>
<span>my popover opener</span>
<span>my popover opener</span>
<span>my popover opener</span>
<Popover isOpen={state.isOpen} body={renderBody} />
```
Because multiple openers can toggle one popover

**Comment by jasonkuhrt** [comment]
@isnifer I created a new `multipleTriggers` example to address your question. Its [listed in the README](https://github.com/littlebits/react-popover) and [here is a direct link](https://littlebits.github.io/react-popover/build/multipleTriggers.html).

**Comment by jasonkuhrt** [comment]
I'll be creating a JSX example shortly.

**Comment by isnifer** [comment]
@jasonkuhrt No, no, no. Your example has no difference with default example.
When I said about multiple triggers, I mean this:
![image](https://cloud.githubusercontent.com/assets/1788245/11690929/e792dee0-9ea9-11e5-9c0b-88a920b73634.png)

Popover should change position depends from his caller. Another example, the same, but another part of interface.
![react_popover](https://cloud.githubusercontent.com/assets/1788245/11691634/f1cf83d8-9eac-11e5-9ed8-0938b13b1643.gif)
JSX example of this demo is here: https://gist.github.com/isnifer/16abd1973ad50b70a292

**Comment by jasonkuhrt** [comment]
@isnifer If I understand you correctly you would just render a `popover` for each row. Nothing special. Does that answer your question?

**Comment by isnifer** [comment]
@jasonkuhrt yeah, but I want only one Popover instance on page :)

**Comment by jasonkuhrt** [comment]
@isnifer Hey, could you explain your use-case in more detail in a new issue please? This issue is about JSX and I will be closing as soon as that is done.

**Comment by isnifer** [comment]
@jasonkuhrt yeah, no problem

**Comment by jasonkuhrt** [comment]
Thanks.

**Comment by jasonkuhrt** [comment]
@uccio83 [source](https://github.com/littlebits/react-popover/blob/master/examples/jsx/main.js) and [demo](https://littlebits.github.io/react-popover/build/jsx.html). Cheers.

**Comment by uccio83** [comment]
Thank you @jasonkuhrt
