### ISSUE TITLE
Disable close animation ? 

### ISSUE THREAD

**Issue by tim-field** [littlebits/react-popover#51]
Is it possible to disable the close animation ?   I'm getting some weird animation flashes when closing from inside a pretty complicated table, would be good to just instantly hide in this case.

**Comment by jasonkuhrt** [comment]
@timbofield Hey. More customizations like this are absolutely reasonable. I would prefer that `react-popover` move toward being a good engine with few forced UX opinions.

**Comment by timbofield** [comment]
![Popover Animation](https://dl.dropboxusercontent.com/u/962209/popover.gif)

**Comment by jasonkuhrt** [comment]
This issue is very old and the provided recording is now a 404. Closing for lack of data to work with. Also because #73 could address this issue.
