### ISSUE TITLE
Multiple target points - one popover instance

### ISSUE THREAD

**Issue by isnifer** [littlebits/react-popover#52]
Discussion started at #50.
When I said about multiple triggers, I mean this:
![image](https://cloud.githubusercontent.com/assets/1788245/11690929/e792dee0-9ea9-11e5-9c0b-88a920b73634.png)
Popover should change position and depends from his caller. 
Another example, the same, but another part of interface.
![react_popover](https://cloud.githubusercontent.com/assets/1788245/11691634/f1cf83d8-9eac-11e5-9ed8-0938b13b1643.gif)
JSX example of this demo is here: https://gist.github.com/isnifer/16abd1973ad50b70a292

**Comment by jasonkuhrt** [comment]
What is the rationale for not wanting to render a Popover per row? Are you hitting performance problems?

**Comment by isnifer** [comment]
I didn't try to test perfomance, but it's obviously. If I have only one popover, I don't want to have that more.

**Comment by isnifer** [comment]
The second argument like a feature, ha-ha. And it's pretty cool

**Comment by jasonkuhrt** [comment]
I have not done benchmarks but the Popover is [managed by React](https://github.com/littlebits/react-popover/blob/master/lib/react-layer-mixin.js#L38-L46) like any other view I think. If you came with clear benchmark data I would be interested in seeing it. I would also be interested to see (not necessarily accept) a PR. But basically I'm not interested in taking on the complexity of manually recycling Popovers when React already does that via its DOM diffing algorithms.

**Comment by jasonkuhrt** [comment]
@isnifer I replaced the Multiple Trigger demo with a Rows demo that relates to this issue. I have taken a screenshot of the resulting DOM (below). I think its reasonable at this stage to not append a `div` for each `popover` regardless of its open state. This is clearly wrong and a good first step to resolve. I still think trying to reuse DOM elements is much more advanced and further complicated by animation timing. If you agree we can make this issue about fixing the latent contains for closed popovers.

![screen shot 2015-12-10 at 10 21 40 am](https://cloud.githubusercontent.com/assets/284476/11719260/ee1236fc-9f27-11e5-9706-5b0b5d25dec8.png)

**Comment by jasonkuhrt** [comment]
I don't think will be worked on in the foreseeable future so I am going to close it.

**Comment by simb4** [comment]
So any approach for possibility of popover to be attached to different elements (Here as well we can reach nice smooth animation). This approach is possible in react-material-ui/Popover, would be nice to have it here as well.

**Comment by simb4** [comment]
The one approach I come up with is to target popover to some div, and if I need need to popover appear here or there, I simply append my div to specified element.
```
        <Popover {...popoverProps}>
          <div ref="pop" style={{position: 'absolute', width: '100%', height: '100%',}}/>
        </Popover>
```
OnClick:
```
onElementClick = (class) => {
    let node = document.getElementsByClassName(class)[0];
    this.togglePopover(true, node);

}
 togglePopover (toState, targetNode) {
   const popoverIsOpen = typeof toState === "boolean"
     ? toState
     : !this.state.popoverIsOpen
   targetNode.appendChild(this.state.popup); // this.state.popup - is DOM element, not the ref
   this.setState({ popoverIsOpen })
 }
```
