### ISSUE TITLE
Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by jasonkuhrt** [littlebits/react-popover#53]
In Chrome and Safari I am seeing a new error when the Popover is dismissed:

```
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.detector.destroy
@ on-resize.js:81uninitialize
@ on-resize.js:29off 
@ on-resize.js:117untrackPopover 
@ index.js:404exit 
@ index.js:295componentDidUpdate 
@ index.js:284chainedFunction 
@ ReactClass.js:542assign.notifyAll 
@ CallbackQueue.js:65ON_DOM_READY_QUEUEING.close 
@ ReactReconcileTransaction.js:81Mixin.closeAll 
@ Transaction.js:202Mixin.perform 
@ Transaction.js:149Mixin.perform 
@ Transaction.js:136assign.perform 
@ ReactUpdates.js:86flushBatchedUpdates 
@ ReactUpdates.js:147wrapper 
@ ReactPerf.js:66Mixin.closeAll 
@ Transaction.js:202Mixin.perform 
@ Transaction.js:149ReactDefaultBatchingStrategy.batchedUpdates 
@ ReactDefaultBatchingStrategy.js:62batchedUpdates 
@ ReactUpdates.js:94ReactEventListener.dispatchEvent 
@ ReactEventListener.js:204
```

I think this [SO Question is related](http://stackoverflow.com/questions/21926083/failed-to-execute-removechild-on-node).

The bug seems to come from the on-resize detector.

**Comment by gregory90** [comment]
I'm also hitting this issue

**Comment by jasonkuhrt** [comment]
Note: So far this bug appears innocuous for the end-user. Annoying at least for the developer.

**Comment by gregory90** [comment]
Actually it does crush my app on path change:
```
Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Comment by jasonkuhrt** [comment]
@gregory90 Thanks for confirming.

**Comment by jasonkuhrt** [comment]
I'm not seeing this error anymore. Re-open if this changes.

**Comment by gregory90** [comment]
Sadly, I'm still seeing this. Nothing changed.

**Comment by jasonkuhrt** [comment]
Are you using the latest release? Any other details you can provide?

**Comment by gregory90** [comment]
I'm using 0.4.4 on Chrome 48. The problem occurs if I have binded function inside popover body. Not sure what other details I can provide?

**Comment by jasonkuhrt** [comment]
>  if I have binded function inside popover body

Can you provide a code example? That would help.

**Comment by gregory90** [comment]
```javascript
diff --git a/examples/jsx/main.js b/examples/jsx/main.js
index 4699d03..7cb815e 100644
--- a/examples/jsx/main.js
+++ b/examples/jsx/main.js
@@ -32,7 +32,7 @@ const Main = React.createClass({
       isOpen,
     } = this.state
     return (
-      <Popover isOpen={isOpen} body='Boo!'>
+      <Popover isOpen={isOpen} body={<div onClick={this.toggle}>Close</div>}>
         <div
           className={ classNames('target', { isOpen }) }
           onClick={this.toggle}>
```
Open popover and then click "Close".

**Comment by jasonkuhrt** [comment]
Thanks! I'll try investigating again.

**Comment by gregory90** [comment]
@jasonkuhrt any news on this? I'd really appreciate it if you take a quick look at this problem.

**Comment by varun-raj** [comment]
I still face this. But only in few places, I'm not able to find the difference from other implementation :/

**Comment by davincho** [comment]
I think I was able to track down the problem.
The error does **not** occur if `children` of the `<Popover>` is static and does not change at all.

Produces error:
```javascript
<Popover
  isOpen={this.state.popOver}
  body={<Select />}>
  <div>{this.state.something}</div>
</Popover>
```
Produce no error:

```javascript
<Popover
  isOpen={this.state.popOver}
  body={<Select />}>
  <div>Static</div>
</Popover>
```

**Comment by knowbody** [comment]
This is exactly the error which I get as well, and it seems that @davincho pointed out to the repro

**Comment by dvkndn** [comment]
Thank you @davincho .

I'm wondering will this PR help? https://github.com/littlebits/react-popover/pull/74

**Comment by davincho** [comment]
@dvkndn Yeah I think this would make the trick.

**Comment by praneshr** [comment]
As @davincho mentioned, it happens only when the children changes.

As a temporary fix, you can do the following

```
<Popover
  isOpen={this.state.popOver}
  body={<Select />}>
  <MakeChildrenAsASeparateClass />
</Popover>

```
Make the children as a separate class and add that as the child to `Popover`

**Comment by jasonkuhrt** [comment]
Hey everyone thanks for the great feedback and notes. So helpful! I am going to try and get #74 merged, just waiting for some git conflicts to be resolved. If need be I'll make a new PR myself in the coming days but I'd like to give a chance for @stephen to get his satisfaction after over a year of no response : P

**Comment by schmooie** [comment]
@jasonkuhrt Any updates on #74? Would love to get this fix in my codebase. Also, thanks for this great lib!

**Comment by jasonkuhrt** [comment]
Closed by https://github.com/littlebits/react-popover/commit/da97510cbda526b5cc0985e47f17791cef782411.

**Comment by a-x-** [comment]
Stil actual due to https://github.com/littlebits/react-popover/issues/187
