### ISSUE TITLE
Build lost module.exports

### ISSUE THREAD

**Issue by KyleAMathews** [littlebits/react-popover#54]
Now have to do `Popover = require('react-popover').default`

If this was intended, it should be a major release.

**Comment by jasonkuhrt** [comment]
Ugh, right. `babel 6` differences. I'll look into it now. Thanks!

**Comment by jasonkuhrt** [comment]
Reference: http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

**Comment by jasonkuhrt** [comment]
Released as `0.4.2`.
