### ISSUE TITLE
If I go to page with popover but *don't* activate it then leave, I get error

### ISSUE THREAD

**Issue by KyleAMathews** [littlebits/react-popover#55]
Error is `Uncaught TypeError: Cannot read property 'removeEventListener' of undefined`

Looks like this is the function: https://github.com/littlebits/react-popover/blob/ae9ca26c7f1a8eca13afe2156ba8029b02fc1913/lib/index.js#L402

**Comment by jasonkuhrt** [comment]
Tell me if I have this right:

* Mount a view that contains an _unopened_ Popover.
* Unmount that view, having never caused said contained Popover to be opened.
* Error

Correct?

**Comment by KyleAMathews** [comment]
Yeah

**Comment by jasonkuhrt** [comment]
Reproduced. Fixing.

**Comment by jasonkuhrt** [comment]
Released `0.4.3`

**Comment by jasonkuhrt** [comment]
@KyleAMathews Thanks.

**Comment by KyleAMathews** [comment]
Just installed 0.4.3—everything seems to be working correctly now.

**Comment by jasonkuhrt** [comment]
:+1:
