### ISSUE TITLE
onOuterAction not working

### ISSUE THREAD

**Issue by leesiongchan** [littlebits/react-popover#56]
Does anybody knows why is
`window.addEventListener('mousedown')`
not working while
`document.addEventListener('mousedown')`
will trigger the mousedown event as expected?

https://github.com/littlebits/react-popover/blob/af3a858622be035a7a21d926f86be9f96afa7a34/lib/index.js#L384

**Comment by jasonkuhrt** [comment]
It is a valid method/event name. It should work. This is the first report of it not working. Can you explain where this is failing for you? Browser vendor? Browser version? Example of your code? Thanks.

**Comment by jasonkuhrt** [comment]
No feedback, closing.

**Comment by RaitoBezarius** [comment]
I have the same problem, I'm using Webpack 1.12.13 with React 0.14 (With Babel and ES6 stuff). I use `react-popover@^0.4.4` version.

I didn't try the `document.addEventListener`, but `window.addEventListener('mousedown')` does not trigger any event for me (tried to break into the handlers, etc...)

I suppose that the event could be swallow by React or something like this.

I could put a minimal repro case by tonight, I think.

**Comment by ziahamza** [comment]
We are also having the same issue on ```react-popover@^0.4.4```. Window events are somehow swallowed, while document events keep firing. And the @leesiongchan fix works. 

@jasonkuhrt , would you be open to a PR that changes window event handlers to document?
