### ISSUE TITLE
pickZone picks the wrong zone.

### ISSUE THREAD

**Issue by ChrisCinelli** [littlebits/react-popover#58]
I have `preferPlace="below"` but on Chrome for Android it is always ignored and always position on `above`. This happen even when the screen is scrolled down and a button is at the top of the viewport. When it is tapped, the popover is shown above the button where nothing is visible.

There is a problem with `doesFitWithin` that return `false` even if there is actually enough space. 
However, at the minimum, if there are no `availZones` the`preferPlace` should be used.

**Comment by ChrisCinelli** [comment]
#59 fix this

**Comment by jasonkuhrt** [comment]
Is this resolved by #60?

**Comment by ChrisCinelli** [comment]
Yes
