### ISSUE TITLE
Popover does not keep the context of the child

### ISSUE THREAD

**Issue by jamesjjk** [littlebits/react-popover#66]
The popover prop body does not keep the context of its children, which makes it difficult to use when the children rely on props with context..

**Comment by clayne11** [comment]
+1

**Comment by fricke** [comment]
Just checking in to see if there's an eta for release on this

**Comment by jamesjjk** [comment]
I have built a version which does

**Comment by fricke** [comment]
@jamesjjk, awesome!  I found it and checking it out.  thanks

**Comment by jasonkuhrt** [comment]
Related to #77. Fixed in #92. Released in [v0.4.5](https://github.com/littlebits/react-popover/releases/tag/v0.4.5)
