### ISSUE TITLE
invalid css?

### ISSUE THREAD

**Issue by tjwebb** [littlebits/react-popover#72]
https://github.com/littlebits/react-popover/blob/v0.4.4/examples/jsx/main.css#L1

None of my build tools, nor my browser, are able to parse this line.

Sass gives me:

```
      @import directive requires a url or quoted path
```

css gives me:

```
Unexpected format../base
```

**Comment by jasonkuhrt** [comment]
We use webpack to build the the examples (https://github.com/littlebits/react-popover/blob/v0.4.4/webpack.config.babel.js).
