### ISSUE TITLE
react-redux connect doesn't work

### ISSUE THREAD

**Issue by juliankrispel** [littlebits/react-popover#77]
Since react-popover sort of maintains it's own lifecycle the [connect](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) hoc doesn't work inside the popover. We created a workaround for this but would really like to see it resolved within react-popover.
I'd gladly help with the changes.

**Comment by pokonski** [comment]
@juliankrispel can you share your fixes?

**Comment by DaveRevay2** [comment]
I'm also interested :)

**Comment by MrBlenny** [comment]
I've found a solution... The problem is that the popover component is being created without the `redux.store` being included in the react component's context.

If you add the following to the of the renderLayer function in the index.js it will work:

```
    /* If we pass array of nodes to component children React will complain that each
    item should have a key prop. This is not a valid requirement in our case. Users
    should be able to give an array of elements applied as if they were just normal
    children of the body component (note solution is to spread array items as args). */
    const store = this.context.store;
    
    // Provide context.store to child elements
    const StoreProvider = class Commit extends _react.Component {
      getChildContext() {
        return {
          store: store
        }
      }
      render() {
        return (
          <div>{this.props.children}</div>
        )
      }
    }
    StoreProvider.childContextTypes = {
      store: _react.PropTypes.object
    }
    
    var popoverBody = (0, _utils.arrayify)(<StoreProvider>{this.props.body}</StoreProvider>);
    const PopupInnerEl = _react.DOM.div(popoverProps, _react.DOM.div.apply(_react.DOM, [{ className: 'Popover-body' }].concat(_toConsumableArray(popoverBody))), (0, _react.createElement)(_tip2.default, tipProps));

    return PopupInnerEl
```

Note that this code now has a JSX dependency so you'll need to transpile it.

If there is a better way I would love to hear it. I am very much a react/redux rookie.

**Comment by timhwang21** [comment]
@MrBlenny Thanks for the fix! @juliankrispel We've run into this issue as well, would be interested in seeing your solution as well.

**Comment by dhassouni** [comment]
@MrBlenny thanks much for your suggestion! I think the non JSX version of your solution is the code below. `	const store = this.context.store;
	
    // Provide context.store to child elements
    const StoreProvider = class Commit extends _react.Component {
      getChildContext() {
        return {
          store: store
        }
      }
      render() {
        return (
			_react.createElement('div', null, this.props.children)
        )
      }
    }
    StoreProvider.childContextTypes = {
      store: _react.PropTypes.object
    }

    var popoverBody = (0, _utils.arrayify)(_react.createElement('StoreProvider', null, this.props.body));
    const PopupInnerEl = _react.DOM.div(popoverProps, _react.DOM.div.apply(_react.DOM, [{ className: 'Popover-body' }].concat(_toConsumableArray(popoverBody))), (0, _react.createElement)(_tip2.default, tipProps));

    return PopupInnerEl`
However, I'm still struggling to get this to work. Has anyone come up with a robust solution or decided on the best way to do this? @juliankrispel we would all love to see what your work-around was as well.

**Comment by MrBlenny** [comment]
I've got my own version now.
https://github.com/MrBlenny/react-popover

This one supports both redux and react-router (store, history and router is added to the context).
Note - this is not compiled. If you npm install it and add it to your project using npm you will need to add it to an exclude list in your webpack config.

**Comment by dhassouni** [comment]
Thanks @MrBlenny. I have myself forked yours with the compiled code (and removing the custom styling which caused me some issues in my use cases). 
See: https://github.com/dhassouni/react-popover
Also, if you want to include it via npm or yarn: https://www.npmjs.com/package/@dhassouni/react-popover

**Comment by jasonkuhrt** [comment]
Hey everyone, this seems like an important issue. Not working with core community libs is a big deal. Now that this project has booted back up, we'll try to make this issue a high priority. Cheers.

**Comment by brandonmp** [comment]
have not attempted this solution yet, but this issue also affects `react-relay` containers for ostensibly same reason. just leaving a note here in case any other `relay` users wander-on by.

**Comment by rafatwork** [comment]
@dhassouni 
Compatibility with both redux & redux-router is what I need. Your fork works splendid in this regard. Thanks.

**Comment by iakovmarkov** [comment]
This also breaks `react-intl` by Yahoo. The reason is the same - context doesn't get passed down.

**Comment by jasonkuhrt** [comment]
I think something like this https://github.com/tajo/react-portal/pull/23 should work for us.

**Comment by jasonkuhrt** [comment]
I think this issue is fixed but if people could confirm by trying out the master branch that would be swell.

**Comment by jasonkuhrt** [comment]
New patch published with fix.
