### ISSUE TITLE
onOuterAction doesn't work Chrome v 51.0.2704.106

### ISSUE THREAD

**Issue by ilyasf** [littlebits/react-popover#78]
onOuterAction doesn't work Chrome v 51.0.2704.106
maybe the reason is 

```
const isOuterAction = (
      !this.containerEl.contains(event.target) &&
      !this.targetEl.contains(event.target)
    )
```

**Comment by xRapidDavex** [comment]
@ilyasf onOuterAction works for me on Chrome 53. You should try running your code against that and see if there's something else wrong or if specifically Chrome 51 is still not working for you.

**Comment by jasonkuhrt** [comment]
Closing. If this is still an issue please re-open with more details. Thanks!
