### ISSUE TITLE
Disable animation

### ISSUE THREAD

**Issue by diegoclearmetal** [littlebits/react-popover#80]
Is there a way to easily disable to the popover animation?  I would like the popover to just appear without the fade/fly-in animation...

**Comment by PascalSenn** [comment]
made a pullrequest for this: https://github.com/littlebits/react-popover/pull/84

**Comment by oyeanuj** [comment]
+1 for this @jasonkuhrt

**Comment by jasonkuhrt** [comment]
Thanks for the input everyone. This project is booting back up and I'm listening. No ETAs to share yet but I think something like this should be possible.

**Comment by jasonkuhrt** [comment]
Duplicate of #73
