### ISSUE TITLE
Is there a way to anchor the popover to the CTA

### ISSUE THREAD

**Issue by brownsmith** [littlebits/react-popover#82]
I would like to anchor the popover to the call to action, so that when a user scrolls the popover travels with the element that opened it, even when it is scrolled off screen. Is this possible?

**Comment by jasonkuhrt** [comment]
I'm not sure what you mean. Could you provide more detail or possibly a screen capture gif showing what you _do not_ want to happen? Thanks!

**Comment by brownsmith** [comment]
Sorry for the late reply, this is no longer a requirement, so it can be closed.

For reference though, when the popover was visible, and I scrolled it to the bottom of the page, it would stay at the bottom of the browser window as the page scrolled underneath it. When this happened, the element that it was positioned absolutely with would be off the screen. Hope that helps.

**Comment by jasonkuhrt** [comment]
@brownsmith Thanks for the info. Useful if I have time to revisit this issue in the future!
