### ISSUE TITLE
Pass a Component to the Popover 'body' prop

### ISSUE THREAD

**Issue by GarrettHartley** [littlebits/react-popover#88]
Is there a way to pass a component as the body prop?

Maybe I am confused but I feel like this should be a common use case.

`							<Popover isOpen={false}
							         body=<MyComponent
											         someProp={true}
									         `/>`
							         place="below"
							         classNames={s.someClassName}
							         refreshIntervalMs={false}
							>`

I get  Uncaught Error: Could not find "store" in either the context or props of "Connect(Select)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Select)".

**Comment by jasonkuhrt** [comment]
Thanks for taking the time to update this issue : )
