### ISSUE TITLE
Just wanted to say thank you

### ISSUE THREAD

**Issue by jonathanmv** [littlebits/react-popover#89]
I couldn't find a proper channel to say **thank you** so I'm creating an issue. You can close it right away. 

I start playing a youtube video after 500ms of mouseover on a thumbnail. It works wonders. I used https://github.com/troybetz/react-youtube for the player

![asd](https://cloud.githubusercontent.com/assets/86024/23393167/ed111738-fd4e-11e6-88e4-f262d1e03d2e.gif)

**Comment by jasonkuhrt** [comment]
@jonathanmv Haha thanks man. I know this project needs a lot of love and that is coming. But I'm happy that some users are finding value with it as is.

Cheers!
