### ISSUE TITLE
Add prefixed-styles support for older browsers

### ISSUE THREAD

**Issue by jasonkuhrt** [littlebits/react-popover#9]
~~https://github.com/littlebits/react-popover/blob/049bfcac1e1b53de7b1ae3ec6f44a5b71218c45f/lib/index.js#L22-L24~~

Issue has changed slightly. We now us no prefixes. So this task is use prefixes generally for older browsers that we think we should support.

**Comment by jasonkuhrt** [comment]
This feature is functionally implemented now 9ba13dc6a2b1cca20e02e627c49a53ddfdb20ce3. But a next step would be to refactor the solution into a coherent API.

**Comment by jasonkuhrt** [comment]
And many thanks @kof for a sensible low-level API.

**Comment by kof** [comment]
:+1:
